"""added email_sent and email_error to shipping group

Revision ID: 110cb7bceefb
Revises: f2e951ce5935
Create Date: 2026-02-04 10:17:21.903242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110cb7bceefb'
down_revision: Union[str, None] = 'f2e951ce5935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_groups', sa.Column('email_sent', sa.Boolean(), nullable=True))
    op.add_column('shipping_groups', sa.Column('email_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping_groups', 'email_error')
    op.drop_column('shipping_groups', 'email_sent')
    # ### end Alembic commands ###
