"""add is_active to article_group, supplier, department, storage_location

Revision ID: 1972542e6129
Revises: 533f7780d545
Create Date: 2026-01-28 14:33:16.155154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1972542e6129'
down_revision: Union[str, None] = '533f7780d545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Für jede Tabelle das gleiche Muster:
    
    # article_groups
    op.add_column('article_groups', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE article_groups SET is_active = TRUE WHERE is_active IS NULL")
    op.alter_column('article_groups', 'is_active', nullable=False)
    
    # suppliers
    op.add_column('suppliers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE suppliers SET is_active = TRUE WHERE is_active IS NULL")
    op.alter_column('suppliers', 'is_active', nullable=False)
    
    # departments
    op.add_column('departments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE departments SET is_active = TRUE WHERE is_active IS NULL")
    op.alter_column('departments', 'is_active', nullable=False)
    
    # storage_locations
    op.add_column('storage_locations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE storage_locations SET is_active = TRUE WHERE is_active IS NULL")
    op.alter_column('storage_locations', 'is_active', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'is_active')
    op.drop_column('storage_locations', 'is_active')
    op.drop_column('orders', 'is_active')
    op.drop_column('departments', 'is_active')
    op.drop_column('article_groups', 'is_active')
    # ### end Alembic commands ###
