"""activity_log_entity_type

Revision ID: 3407ed3df3af
Revises: cbe905862690
Create Date: 2026-02-04 13:27:46.322913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3407ed3df3af'
down_revision: Union[str, None] = 'cbe905862690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    
    op.add_column('activity_logs', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('activity_logs', sa.Column('entity_id', sa.UUID(), nullable=True))
    
    
    op.execute("UPDATE activity_logs SET entity_type = 'order', entity_id = order_id")
    
    
    op.alter_column('activity_logs', 'entity_type', nullable=False)
    op.alter_column('activity_logs', 'entity_id', nullable=False)
    
  
    op.drop_constraint('activity_logs_order_id_fkey', 'activity_logs', type_='foreignkey')
    op.drop_column('activity_logs', 'order_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('activity_logs_order_id_fkey'), 'activity_logs', 'orders', ['order_id'], ['id'])
    op.drop_column('activity_logs', 'entity_id')
    op.drop_column('activity_logs', 'entity_type')
    # ### end Alembic commands ###
