"""empty message

Revision ID: 45d1f71b97f2
Revises: 1972542e6129
Create Date: 2026-01-29 13:27:28.838050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d1f71b97f2'
down_revision: Union[str, None] = '1972542e6129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('shipping_group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'shipping_groups', ['shipping_group_id'], ['id'])
    op.add_column('orders', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('orders_shipping_group_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_supplier_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'supplier_id')
    op.drop_column('orders', 'shipping_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_group_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_supplier_id_fkey'), 'orders', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(op.f('orders_shipping_group_id_fkey'), 'orders', 'shipping_groups', ['shipping_group_id'], ['id'])
    op.drop_column('orders', 'is_active')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'shipping_group_id')
    op.drop_column('order_items', 'supplier_id')
    # ### end Alembic commands ###
