"""add article_group table and article notes

Revision ID: 533f7780d545
Revises: eaa6ff59a43c
Create Date: 2026-01-28 12:49:07.354285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533f7780d545'
down_revision: Union[str, None] = 'eaa6ff59a43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Erst die article_groups Tabelle erstellen
    op.create_table('article_groups',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    
    op.execute("INSERT INTO article_groups (id, name) VALUES (gen_random_uuid(), 'Sonstige')")
    op.add_column('articles', sa.Column('article_group_id', sa.UUID(), nullable=True))
    op.add_column('articles', sa.Column('notes', sa.Text(), nullable=True))
    op.execute("UPDATE articles SET article_group_id = (SELECT id FROM article_groups WHERE name = 'Sonstige')")
    op.alter_column('articles', 'article_group_id', nullable=False)
    op.create_foreign_key(None, 'articles', 'article_groups', ['article_group_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'notes')
    op.drop_column('articles', 'article_group_id')
    op.drop_table('article_groups')
    # ### end Alembic commands ###
