"""add reservation_summaries

Revision ID: 6721a2d2770e
Revises: 3407ed3df3af
Create Date: 2026-02-05 16:08:14.583039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6721a2d2770e'
down_revision: Union[str, None] = '3407ed3df3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.Enum('MITTAG', 'ABEND', name='timeslot'), nullable=False),
    sa.Column('total_reservations', sa.Integer(), nullable=False),
    sa.Column('total_guests', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_date', 'time_slot', name='uq_date_timeslot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_summaries')
    # ### end Alembic commands ###
