"""storage_location_department_not_null

Revision ID: bcf0cb208d11
Revises: 45d1f71b97f2
Create Date: 2026-02-03 17:39:54.196776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf0cb208d11'
down_revision: Union[str, None] = '45d1f71b97f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storage_locations', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storage_locations', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
