"""deleted is_major_event from activity_log

Revision ID: cbe905862690
Revises: 110cb7bceefb
Create Date: 2026-02-04 12:23:21.392350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe905862690'
down_revision: Union[str, None] = '110cb7bceefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'is_major_event')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('is_major_event', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
