"""empty message

Revision ID: eaa6ff59a43c
Revises: f63e99ceaf84
Create Date: 2026-01-27 15:33:46.630499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa6ff59a43c'
down_revision: Union[str, None] = 'f63e99ceaf84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('totp_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_2fa_enabled = FALSE WHERE is_2fa_enabled IS NULL")
    op.alter_column('users', 'is_2fa_enabled', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_2fa_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
