"""empty message

Revision ID: f2e951ce5935
Revises: bcf0cb208d11
Create Date: 2026-02-03 18:54:01.656547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e951ce5935'
down_revision: Union[str, None] = 'bcf0cb208d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_groups', sa.Column('pdf_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping_groups', 'pdf_path')
    # ### end Alembic commands ###
